# ZenkaiOS Common Configuration

PRODUCT_BRAND := ZenkaiOS
PRODUCT_SYSTEM_NAME := ZenkaiOS
PRODUCT_MANUFACTURER := ZenkaiOS

ZENKAI_VERSION := 1.0
ZENKAI_CODENAME := Ichi

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.zenkai.version=$(ZENKAI_VERSION) \
    ro.zenkai.codename=$(ZENKAI_CODENAME)
